config/routes.rb
Rails.application.routes.draw do
  resources :accounts

  get "/login", to: "sessions#new", as: "login"

  post "/login", to: "sessions#create", as: "sessions"

  delete "/logout", to: "sessions#destroy", as: "logout"

  root 'expenses#new'

  resources :expenses

end

app/models/account.rb
class Account < ActiveRecord::Base
  has_secure_password
  validates_presence_of :username
  validates_presence_of :email
  validates_presence_of :password
  validates_uniqueness_of :username
  validates_uniqueness_of :email
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create

  has_many :expenses

end

app/models/expense.rb
class Expense < ActiveRecord::Base

  CATEGORIES = ["Travel", "Meals", "Office supplies", "Other"]

  validates_presence_of :amount
  validates_presence_of :merchant_name
  validates_presence_of :purchased_on
  validates_presence_of :category
  validates_presence_of :description

  belongs_to :account

  mount_uploader :receipt, ReceiptUploader

end

app/models/session.rb
class Session
  include ActiveModel::Model
  def username
  end
  def password
  end



  def initialize(username = nil, password = nil)
    @username = username
    @password = password
  end

  def can_login?
    username_correct? && password_correct?
  end

  private

# the following methods have to happen in this order, otherwise they don't know what @account is
  def username_correct?
    not account.nil?
  end

  def password_correct?
    account.authenticate(@password)
  end

  public

  def account
    @account ||= Account.find_by_username(@username)
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    if current_account.admin == true
      @accounts = Account.all
    else
      flash[:alert] = 'Bugger off'
      redirect_to root_path
    end
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:username, :password, :password_confirmation, :email)
    end

    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :require_login


 
  private

  def require_login
    unless logged_in?
      flash[:error] = "You must be logged in to access this section"
      redirect_to login_path # halts request cycle
    end
  end


  def logged_in?
    s = session[:account_id]
    if s
      Account.find(s)
    else
      false
    end
  end

  def current_account
    @current_account ||= Account.find(session[:account_id])
  end

end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  
  def new
    @expense = Expense.new
  end

  def create
    @expense =  current_account.expenses.build(expense_params)
    if @expense.save
      redirect_to @expense, notice: 'Expense was successfully created.'
    else
      logger.debug "Expense didn't save because: #{@expense.errors.inspect}"
      render :new
    end
  end

  def expense_params
    params.require(:expense).permit(:amount, :merchant_name, :purchased_on, :category, :description, :receipt)
  end

  def show
    @expense = Expense.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :require_login, only: [:new, :create]

  def new
    @session = Session.new
  end

  def create
    @session = Session.new(params[:session][:username], params[:session][:password])
    if @session.can_login?
      session[:account_id] = @session.account.id
      redirect_to root_path
    else
      flash.now[:alert] = 'Invalid email or password'
      render :new
    end
  end

  def destroy
    session.delete(:account_id)
    redirect_to root_path
  end


end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Accounts</h1>

<table class="table">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.username %></td>
        <td><%= account.email %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @account.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @account.email %>
</p>

<p>
  <strong>Expenses:</strong>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Merchant Name</th>
        <th>Expense Amount</th>
        <th>Purchase Date</th>
        <th>Category</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
      <% @account.expenses.each do |expense| %>
        <tr>
        <td><%= expense.merchant_name %></td>
        <td><%= number_to_currency(expense.amount) %></td>
        <td><%= expense.purchased_on %></td>
        <td><%= expense.category %></td>
        <td><%= expense.description %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

app/views/expenses/new.html.erb
<%= form_for(@expense) do |f| %>

  <div class="form-group">
    <%= f.label :amount %>
    <%= f.number_field :amount, class: "form-control", placeholder: "Amount" %>
  </div>
  <div class="form-group">
    <%= f.label :merchant_name %>
    <%= f.text_field :merchant_name, class: "form-control", placeholder: "Merchant Name" %>
  </div>
  <div class="form-group">
    <%= f.label :purchased_on %>
    <%= f.date_field :purchased_on, class: "form-control", placeholder: "Purchase Date" %>
  </div>
  <div class="form-group">
    <%= f.label :category %>
    <%= f.select("category", Expense::CATEGORIES, {include_blank: true}) %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control", placeholder: "Description" %>
  </div>
  <div class="form-group">
    <%= f.label :receipt %>
    <%= f.file_field :receipt %>
  </div>


  <button type="submit" class="btn btn-primary">Submit</button>


<% end %>

app/views/expenses/show.html.erb
<p>
  <strong>Amount:</strong>
  <%= number_to_currency(@expense.amount) %>
</p>

<p>
  <strong>Merchant Name:</strong>
  <%= @expense.merchant_name %>
</p>

<p>
  <strong>Purchase Date:</strong>
  <%= @expense.purchased_on %>
</p>

<p>
  <strong>Expense Category:</strong>
  <%= @expense.category %>
</p>


<p>
  <strong>Description:</strong>
  <%= @expense.description %>
</p>

<p>
  <strong>Receipt:</strong>
  <br> <!-- for coffee and a cigarette -->
  <%= link_to(image_tag(@expense.receipt.thumb.url), @expense.receipt.url, html_options = {}) %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Uitgaven</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>

  <div class="container">

    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Uitgaven</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapsede navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Log In", login_path %></li>
        <li><a href="#">Link</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Log out", logout_path, method: "delete" %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


  <% if flash[:notice] %>
    <div class="alert alert-success" role="alert">
      <div><%= flash[:notice] %></div>
    </div>
  <% end %>

  <% if flash[:alert] %>
    <div class="alert alert-danger" role="alert">
      <div><%= flash[:alert] %></div>
    </div>
  <% end %>

    <%= yield %>

  </div>

</body>
</html>